language: python
python:
  - "nightly"
  - "3.11"
  - "3.10"
  - "3.9"
  - "3.8"
  - "3.7"
  - "pypy3"

matrix:
  allow_failures:
    - os: osx
  include:
    - name: "Python 3.11 on Xenial Linux"
      python: 3.11 # this works for Linux but is ignored on macOS or Windows
      dist: xenial # required for Python >= 3.7
    - name: "Python nightly on Xenial Linux"
      python: nightly # this works for Linux but is ignored on macOS or Windows
      dist: xenial # required for Python >= 3.7
    - os: osx
      osx_image: xcode8
      python: 3.11
    - os: osx
      osx_image: xcode9
      python: 3.11
    - os: osx
      osx_image: xcode10
      python: 3.11
    - os: osx
      osx_image: xcode11
      python: 3.11

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest tests
